version: "3.9"

services:
  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ticketing_backend
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  # Vue Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ticketing_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  # MySQL
  db:
    image: mysql:8.0
    container_name: ticketing_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ticketing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
